# Generated by Django 5.2.5 on 2026-02-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagram',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='diagram_previews/'),
        ),
    ]
