# Generated by Django 5.2.5 on 2025-09-28 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_make_email_unique'),
        ('user', '0002_remove_user_access_token'),
    ]

    operations = [
    ]
