# Generated by Django 5.2.5 on 2025-12-14 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_merge_20250928_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='provider',
            field=models.CharField(choices=[('email', 'Email/Password'), ('google', 'Google'), ('github', 'GitHub')], default='email', max_length=10),
        ),
    ]
