# Generated by Django 5.2.5 on 2026-03-23 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ai_diagram_requests_limit',
            field=models.IntegerField(default=10),
        ),
    ]
